[build]
publish = "."
functions = "netlify/functions"

[functions]
node_bundler = "esbuild"
external_node_modules = ["firebase-admin", "node-fetch", "nodemailer"]

# Environment variables will be set in the Netlify dashboard
# SMTP_HOST
# SMTP_USER
# SMTP_PASSWORD
